<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class AddressResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id'          => $this->id,
            'label'       => $this->label,
            'value'       => $this->value,
            'unrestricted_value' => $this->unrestricted_value,
            'line1'       => $this->line1,
            'line2'       => $this->line2,
            'city'        => $this->city,
            'postal_code' => $this->postal_code,
            'country' => $this->country,
            'country_iso_code' => $this->country_iso_code,
            'federal_district' => $this->federal_district,
            'region_fias_id' => $this->region_fias_id,
            'region_kladr_id' => $this->region_kladr_id,
            'region_iso_code' => $this->region_iso_code,
            'region_with_type' => $this->region_with_type,
            'region_type' => $this->region_type,
            'region_type_full' => $this->region_type_full,
            'region' => $this->region,
            'area_fias_id' => $this->area_fias_id,
            'area_kladr_id' => $this->area_kladr_id,
            'area_with_type' => $this->area_with_type,
            'area_type' => $this->area_type,
            'area_type_full' => $this->area_type_full,
            'area' => $this->area,
            'city_fias_id' => $this->city_fias_id,
            'city_kladr_id' => $this->city_kladr_id,
            'city_with_type' => $this->city_with_type,
            'city_type' => $this->city_type,
            'city_type_full' => $this->city_type_full,
            'settlement_fias_id' => $this->settlement_fias_id,
            'settlement_kladr_id' => $this->settlement_kladr_id,
            'settlement_with_type' => $this->settlement_with_type,
            'settlement_type' => $this->settlement_type,
            'settlement_type_full' => $this->settlement_type_full,
            'settlement' => $this->settlement,
            'street_fias_id' => $this->street_fias_id,
            'street_kladr_id' => $this->street_kladr_id,
            'street_with_type' => $this->street_with_type,
            'street_type' => $this->street_type,
            'street_type_full' => $this->street_type_full,
            'street' => $this->street,
            'house_fias_id' => $this->house_fias_id,
            'house_kladr_id' => $this->house_kladr_id,
            'house_type' => $this->house_type,
            'house_type_full' => $this->house_type_full,
            'house' => $this->house,
            'block_type' => $this->block_type,
            'block_type_full' => $this->block_type_full,
            'block' => $this->block,
            'flat_type' => $this->flat_type,
            'flat_type_full' => $this->flat_type_full,
            'flat' => $this->flat,
            'entrance' => $this->entrance,
            'floor' => $this->floor,
            'intercom' => $this->intercom,
            'lat'         => $this->lat,
            'lng'         => $this->lng,
            'fias_id' => $this->fias_id,
            'kladr_id' => $this->kladr_id,
            'qc_geo' => $this->qc_geo,
            'timezone' => $this->timezone,
            'beltway_hit' => $this->beltway_hit,
            'beltway_distance' => $this->beltway_distance,
            'metro' => $this->metro_json,
            'raw_dadata' => $this->raw_dadata_json,
            'geo_source' => $this->geo_source,
            'geocoded_at' => $this->geocoded_at,
        ];
    }
}
